### ISSUE TITLE
When there are no polygons, the polygon SHP is not exported, but the (empty) polygon KML is created

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool#194]
For example: https://demo-data.humdata.org/dataset/cjtest06_e_a_points_of_interest_ea

I guess the desired behavior would be to not create resources for any geometry for which there are no records in the export region?

**Comment by bdon** [comment]
I have noticed this as well. This is an artifact of how GDAL/OGR behaves. Ideally, we'd omit the resource if it is empty - this will require inspecting the file itself as I don't think this information is passed in a structured way through ogr2ogr's STDOUT.

In the case where we omit the resource, we should surface the omission to the user to distinguish between the correct behavior (the resource missing) and erroneous behavior.

**Comment by cjhendrix** [comment]
Yes, that's a good idea.  In those cases, maybe we could add an a line to the default dataset description.  Something like _No features were found for one or more feature types (point, line, polygon) in the extent of this export.  Resources were not created for those feature types._

**Comment by mataharimhairi** [comment]
@bdon Are empty KML files still being generated? If so, has the suggested message '_No features were found for one or more feature types (point, line, polygon) in the extent of this export. Resources were not created for those feature types._ been added to notify users?

**Comment by bdon** [comment]
I have changed the behavior to show "Empty" for the status instead of "Failed" when there is no matching OSM data for the selected region.

For the HDX case I predict that the regions and feature selections are curated enough that there should not be a case where a feature type is totally empty.

**Comment by bdon** [comment]
https://github.com/hotosm/osm-export-tool-python now always creates a file for all output layers, even if no features will be written to it
