### ISSUE TITLE
Accented characters are allowed in the dataset name portion of the title, but not the theme portion

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool#195]
This is a minor issue since all of our dataset names are in English.  But if the code is ever used elsewhere it might force non-English speakers to have misspelled titles.

**Comment by bdon** [comment]
I slugify all theme names using ASCII because I wasn't sure how downstream formats such as Shapefiles and KML handle Unicode theme names. If these formats allow it, we should be able to let unicode names through

**Comment by cjhendrix** [comment]
That's a great point.  KML is probably fine but shapefiles are antique and some systems might not like non-ascii.  As it's a minor issue for us, I suggest we leave it alone for now.

**Comment by mojodna** [comment]
The first step was allowing Unicode theme names through in the YAML (they still get slugified as ASCII): a3820767aafde2a6392a5013d02b84cd46b8d4a6

**Comment by bdon** [comment]
https://github.com/hotosm/osm-export-tool-python supports unicode theme names now. Unknown if HDX supports unicode dataset names, but no themes as of right now have non-ASCII characters.
