### ISSUE TITLE
Option to Export All OSM Data in Shapefile and Geopackage

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#239]
Only way to export all OSM features is through a OSM.pbf or OSM.xml file format, but I think having it as Geopackage and Shapefile would be good too. Some data is lost during the conversion, but the option should be there. Its important for people trying to assess whats in the data, in order to figure out what could even be filtered in the future.

Can we please create an ‘All’ option at the top of the tree, above ‘Buildings’. With a hint popping up when hovering over the ‘All’ button stating something along the lines that 'selects all OSM data available in the database, but some may be lost during transformation into Shapefile, etc'

<img width="1392" alt="screen shot 2017-09-06 at 13 46 51" src="https://user-images.githubusercontent.com/8972913/30134283-7469d06a-930b-11e7-856d-f0227a383759.png">

**Comment by mataharimhairi** [comment]
@ivangayton (need to add him to the HOT organisation).

After discussing this with @mojodna and @bdon, it appears that grabbing all the OSM data for an AOI in a .shp of .gpkg isn't really feasible. This is because the attribute columns have to be predefined for the conversion from .pbf file.

Therefore if the user would like to extract everything to see what features are available, it would be best to do so as a .pbf or .xml file and then predefine the feature selection via YAML on the '3 Data' tab, while creating the export in .shp and/or .gpkg.

**Comment by mataharimhairi** [comment]
@brandon would it be possible to use the columns predefined by GeoFabrik to create an ‘ALL’ shapefile?

**Comment by bdon** [comment]
wouldn't that be substantially different than "all" columns defined by our spreadsheet? instead, if people need the same Geofabrik schema, that should be defined as a saved feature selection

**Comment by mataharimhairi** [comment]
there are several saved feature selection 'data models' that i would like to develop with input from the community. so perhaps a 'GeoFabrik' data model/schema would be the way forward for now. Once I created them, is there a way that we can feature - say 6 data models/schemas on the configuration page easily? Thanks @bdon

**Comment by bdon** [comment]
We can add a "Pinned" flag accessible by admins that will always be at the top?

**Comment by bdon** [comment]
added "pinned" flag that will make that feature selection appear first

**Comment by mataharimhairi** [comment]
Will give this a go, once I get round to developing the data model/schema's. Might not be for a couple more weeks. Have several big reports due! Thanks @bdon
