### ISSUE TITLE
Page Displaying Priority Export Jobs

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#243]
Should we have a page or section that can feature high priority export jobs, related to HOT activations for onset disasters?

Perhaps on the About page?

**Comment by bdon** [comment]
How would "high priority" be determined?

**Comment by mataharimhairi** [comment]
There would probably have to be the option on the export to make it high priority. Perhaps this could be done through the admin interface to select exports for 'high priority' so only higher level users can access it.

**Comment by mataharimhairi** [comment]
@bgirardot Correct me if I am wrong, but the new TM will have a status page for activations which will be able to host links to associated export datasets?

If this is the case, than it probably isn't needed on the export tool itself, as users can go to the export page and filter based on activation.

**Comment by mataharimhairi** [comment]
@bdon just revisiting this issue. is it possible to provide access to some admin users to display featured exports on the home page?

**Comment by bdon** [comment]
Feature request: also have a way to "feature" certain YAMLs

**Comment by mataharimhairi** [comment]
@bdon allowing users to feature YAMLs is not as important as having default ones in everyones configuration library https://github.com/hotosm/osm-export-tool/issues/310

It would be good to allow users to feature export jobs though. Again this should only be available to admin users, along with the capability to export over the limit of jobs per hour and create permalinks. This is all focuses around admin users creating jobs for disaster responses and projects to share with partners.

**Comment by bdon** [comment]
@mataharimhairi Staging now has a field called "Pinned" on Jobs and Saved Feature Selections:

<img width="1426" alt="Screen Shot 2019-11-12 at 11 42 04 PM" src="https://user-images.githubusercontent.com/77501/68733881-27e12d00-05a6-11ea-8aec-4fdb57fce2fb.png">

Checking this box and Saving the form will cause the Job or Feature Selection to appear first in the list with a star:

<img width="725" alt="Screen Shot 2019-11-12 at 11 42 24 PM" src="https://user-images.githubusercontent.com/77501/68733898-39c2d000-05a6-11ea-80d0-ff376dd31916.png">

This is the simplest way to implement this, let me know if you have other suggestions

**Comment by mataharimhairi** [comment]
@bdon is it possible for Admin users to 'pin' certain jobs through the main tool interface without having to go into the admin interface? this would be nice but is not as important as the request below.

i was also hoping that the 'pinned' jobs would be displayed on the 'About' page, instead of the 'Exports' page. this is because they would be (for example disaster related exports) featured datasets generated by the export tool.

and would be aimed at people being directed to the export tool who might not be users of the tool and are unfamiliar with the navigation. its a way for them to find important exports quickly, select them and then sign up, etc.

**Comment by bdon** [comment]
@mataharimhairi The main tool interface doesn't have any UI for Admin functionality or editing exports after they are created, so I think this functionality must live in the /admin section. This is live now on export.hotosm.org
