### ISSUE TITLE
some large area exports with lots of tag filters hang indefinitely on Overpass query

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool#252]
https://github.com/drolbr/Overpass-API/issues/437

For now, I have added a 20 minute timeout to all HTTP requests to overpass, although this shouldn't be necessary

**Comment by bdon** [comment]
I was not able to reproduce this problem on a new AWS instance with 16GB of ram. This was running on the instance itself and not inside a Docker container. Will continue testing to try to reproduce.

**Comment by bdon** [comment]
I'm pretty sure at this point that this is related to resource exhaustion, related to big queries on very dense areas such as Japan and Western Europe. A potential fix is to enforce a limit on maximum # of nodes in the AOI rather than a maximum spatial extent in kilometers.

An example limit is 30 million nodes for the bbox of the AOI. This can be answered in 10-20 seconds by Overpass, and be run as a validation step before a user can create an export. 30 million nodes is enough to contain all of Kenya, but not enough contain all of Belgium

**Comment by bdon** [comment]
Current thinking is to query for the total # of nodes on export submit, if the area is over some threshold. if too many nodes, reject the request

**Comment by bdon** [comment]
resolved by using libcurl instead of requests

**Comment by Dennisboyangzhang** [comment]
> resolved by using libcurl instead of requests

Could you please share some details about your solution?  I'm having the same issue now.

**Comment by bdon** [comment]
https://github.com/hotosm/osm-export-tool/commit/3c310bd6affe571d00dd461498e9f087d8291f97

In this case, I just call `curl` via `subprocess` instead of using Python Requests.
