### ISSUE TITLE
UI should accept featurecollections with one polygon feature

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool#254]

**Comment by verdy-p** [comment]
I don't think we really need feature collections (or its "properties" can be simply ignored). However the export tool still needs a valid geometry which can only be one or more "Polygon" or just one "MultiPolygon" containing all of them (as the coordinates in "MultiPolygon" in geoJSON, is just a simple array of coordinates in a "Polygon", you just concatenate the arrays separated by comma and surrounded by [])
