### ISSUE TITLE
Stuck on Spinning Wheel When Not Logged In

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#256]
The Export Tool seems to be stuck on a spinning wheel when users are not logged in with no direction message, which can be confusing (see image).

This spinning wheel keeps on going until the user clicks the 'Login' button, but there is no prompt to direct users as to what to do. This needs to be added in.

<img width="1280" alt="screen shot 2017-10-02 at 22 09 54" src="https://user-images.githubusercontent.com/8972913/31110878-eebb19d8-a7be-11e7-8082-6fa26e7df8e8.png">

**Comment by mojodna** [comment]
Proposal: remove "Logging you in..." text on login interstitial and potentially clarify that a popup window should have opened and to click if it didn't.
