### ISSUE TITLE
Move "unfiltered" ("all") option to Data tab

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool#258]
Formats that are not produced by `ogr2ogr` (MWM, OBF, PBF, IMG) will happily deal with "all" data. The default expectation should be that they're filtered using the feature selections (matching behavior elsewhere).

@bdon what do you think about the best way to implement this? Option per format (which then uses `UnfilteredPBF`) or configurable prerequisites?

**Comment by mataharimhairi** [comment]
@bdon what are you current thoughts on this issue?

**Comment by bdon** [comment]
This is a duplicate of #311, I think it will be unnecessary because the new backend uses "unfiltered" PBFs for all formats.
