### ISSUE TITLE
Feature Button on Existing Exports Not Working

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#265]
The 'Feature' button at the bottom left corner of the Export job page doesn't seem to be working. The 'Re-Run', 'Clone' and 'Delete' buttons are working, but the 'Feature' button doesn't bring up the YAML syntax used for the job, like it should do.

**Comment by mojodna** [comment]
This seems to have been fixed in 97a3ad1. If it's still problematic, can you share the export URL that's problematic?

**Comment by mataharimhairi** [comment]
It seems to be the case on all of the exports. Just go to the Export page and select any job to test:

https://export.hotosm.org/en/v3/exports/6d3f88aa-1c78-494d-927d-c64ab09fb2b4

https://export.hotosm.org/en/v3/exports/7e6878c0-58e8-4eac-876b-ccf33eaa8a05

**Comment by mojodna** [comment]
I discovered I was using a cached copy; after closing it, I managed to reproduce it and fixed it in 48168cb, which @bdon is deploying soon.
