### ISSUE TITLE
Limit Description Character Count in Export Table

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#267]
Some users are writing very long descriptions for their exports, which is good to provide insight to other users. However it doesn't look good in the table on the Export page. Could we limit the number of characters shown in the table?

<img width="1418" alt="screen shot 2017-10-09 at 18 47 44" src="https://user-images.githubusercontent.com/8972913/31365858-c7e8deda-ad22-11e7-8e73-d01ee8761a91.png">

**Comment by mojodna** [comment]
http://blueprintjs.com/docs/#core/components/text looks good for this (`@blueprintjs/core` is already a dependency)

**Comment by mojodna** [comment]
`Text` was applying CSS properties and causing the cell to expand, so I added ellipsis manually (truncating around 40 characters at word boundaries).

![image](https://user-images.githubusercontent.com/45/31399406-07cb5e32-ada1-11e7-8165-c76e14236c9e.png)
