### ISSUE TITLE
Configuration Doesn't Appear on '03 Data' Tab

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#268]
The tab to select 'Stored Configurations' during the feature selection phase doesn't appear:

<img width="1392" alt="screen shot 2017-10-09 at 18 54 48" src="https://user-images.githubusercontent.com/8972913/31365984-8907ba3c-ad23-11e7-8bda-428d3602e4d4.png">

**Comment by mojodna** [comment]
Fixed in a1dd522
