### ISSUE TITLE
Admin Interface for Tool Metrics

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#273]
Currently there isn't an easy way for managers to find out which file format is most downloaded? An easy to use solution, such as an admin interface for pulling tool metrics should be considered.

This would look at things such as the number of downloads (daily, weekly, monthly), number of file formats and region/country download numbers.

**Comment by bdon** [comment]
Let's make a script to build this report first that can be run "offline", as integrating it into the UI would be much more involved

**Comment by mataharimhairi** [comment]
A preliminary stats page for the Export Tool has been set up at https://export.hotosm.org/en/v3/stats, which needs to be reviewed and feedback provided.

**Comment by mataharimhairi** [comment]
@bdon thanks for the initial setup for the stats page. as discussed a couple weeks ago, it would be great if there was a bigger time range on the stats, so that you can also look at the past year and potentially even up to 2, 3, and 5 years if possible. 

![Screen Shot 2019-10-15 at 17 13 10](https://user-images.githubusercontent.com/8972913/66818801-70d69f00-ef70-11e9-8117-55058ff41954.png)

It would also be very beneficial if this information could be exported into a .csv. I also notice that there are areas highlighted on the map - is this highlighting users and/or exports from the last day, week or month? this information would also be good to export as a GeoJSON if possible.

Here is the list of ideal stats that could be provided on the tool as outlined in the SoW:


Stats Tool
--
no. of visitors no. of unique visitors geospatial distribution of visitors (city, country, continent)most visited page most time spent on page no. of jobs created no. of downloads no. of file formats exportedtypes of features exportedmost downloaded jobgeospatial distribution of jobs created (city, country, continent)geospatial distribution of jobs downloaded (city, country, continent)
* all of the stats should be able to be filtered and disaggregated based on day/week/year

**Comment by bdon** [comment]
* No. of visitors, No. of unique visitors, geospatial distribution, most visited page, most time spent on page -> we don't have that information as we aren't doing any user tracking (google analytics piwik etc) 
* We also don't have any historical information on the number of downloads, nor are we tracking that; since all downloads are public, that is simply served though the NGINX web server. There may be download stats in the HDX system though. 
* I'm working on: no. of file formats exported
Types of features exported: there isn't an obvious way to classify this because the number of categories is effectively infinite, but I can instead do a histogram analysis of the most common mentioned tag in the feature YAML
* is it correct to assume we should ignore the HDX and Partner jobs in these metrics?
* for Most downloaded job, see above; no download info available.
* Geospatial distribution of jobs created: I can do a reverse geocode of geometry centroid -> geonames city, admin1 and country code
* geospatial distribution of job downloaded: again, no download info available.

**Comment by mataharimhairi** [comment]
@bdon correct, that HDX and Partner jobs should be ignored in these metrics. as for No. of visitors, No. of unique visitors, geospatial distribution, most visited page, most time spent on page, is there a way we can extract this information from Matomo and combine it in the downloadable stats .csv file.

@dakotabenjamin just looping in you in here to help support brandon regarding what stats can be extracted through Matomo set up for some of the HOT tools (https://matomo.hotosm.org/). I know  this hasn't been investigated or initiated fully, but this might be a good opportunity to see how it can support the Export Tool to provide insightful user stats.

**Comment by mataharimhairi** [comment]
@bdon just adding our conversation here for reference. is it possible to have a top page option (along with ‘About’, ‘Learn’, ‘Create’, etc) for ‘Admin’ which would provide a link to the admin (‘Manage’) page, as well as the ‘Stats’ page. this would make it easier for admin users find the right pages to access these pages and tidy things up a bit.

**Comment by mataharimhairi** [comment]
Adding the 'Dev : 4.0' tag to this issue so that it is flagged for inclusion in the next round of development. The tidy up of the options available on the top bar can be addressed when a new re-write of the UI is carried out based on the UI design work carried out by Jian #313

**Comment by mataharimhairi** [comment]
Opened a separate issue for the last comment.

**Comment by bdon** [comment]
@mataharimhairi based on our discussion I have added:
* choosing between day/week/month aggregation.
* Top Regions shows the 5 top country codes exported that day, based on AOI centroid.
* All AOI centroids for the selected date range are shown on the map. 
* CSV Output will export the same data as seen on the table, which can be visualized in Excel/Google Sheets. 

Stats based on sub-national regions such as cities are too noisy to be meaningful, and this information can be gleaned via the map visualization. 

Screenshot:
<img width="1330" alt="Screen Shot 2019-11-30 at 6 24 39 PM" src="https://user-images.githubusercontent.com/77501/69907206-af98ab00-139e-11ea-8eaf-8451f36ee69d.png">

Live now in prod on https://export.hotosm.org/en/v3/stats

**Comment by bdon** [comment]
@mataharimhairi here is a link to the total breakdown of exports by country: https://docs.google.com/spreadsheets/d/1iKXtP3aog0jPQYYGumpDiQgFJaSIqi8iXvo0irEZQM8/edit#gid=1167681852

**Comment by mataharimhairi** [comment]
Do you have a list of the Region ID long names, so the user can determine which region (and countries that are contain within the region) it is?

**Comment by bdon** [comment]
@mataharimhairi they are ISO-3166 country codes: http://download.geonames.org/export/dump/countryInfo.txt
