### ISSUE TITLE
Export -> KML -> maps.me

### ISSUE THREAD

**Issue by bjohas** [hotosm/osm-export-tool#274]
Hello,

when I export to KML, and use this as bookmarks, the list of bookmark(-files) (in maps.me) doesn't show a name. I can still click the blank space and see the imported data, but it would be good if the list of bookmark-files showed a relevant string.

The KML (as generated) has:
<Folder><name>SELECT</name>

but maps.me expects
<name>SELECT</name>
(at top level). 

Hope that's not incompatible with the KML spec.

Obviously the name should be set to something relevant, even if it's just something generic "OSM Export".

Great tool - many thanks!

**Comment by bdon** [comment]
@bjohas can you link me to the URL of the export where you saw this?

**Comment by bdon** [comment]
KML layers now have meaningful names:

<img width="336" alt="Screen Shot 2019-10-18 at 10 37 43 AM" src="https://user-images.githubusercontent.com/77501/67103550-5defe480-f193-11e9-8620-217afd000be3.png">
