### ISSUE TITLE
Suggestions for improving UI on individual Export page

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool#276]
![2017-11-17_04h22_58](https://user-images.githubusercontent.com/265831/32927876-630c7c9c-cb4f-11e7-9fe2-5ac9df2205b8.png)

As a user, I do not really care about the long string of alpha numeric characters the system uses to identify and keep track of jobs and runs, they should not be the "top", highlighted UI item.

What I as a user care about is the name of the export and the date/time of the last run so it is immediately clear to me what the "latest" run is.

I would suggest switching the data in the two fields for each info panel as marked above to highlight the most relevant, human readable information and de-emphasize the really user unfriend long alpha numeric string the system uses for tracking things.

**Comment by bdon** [comment]
This change is live now on export-staging.hotosm.org
