### ISSUE TITLE
Had trouble logging in and then got old UI error screen

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool#277]
Just thought you might want to know, I only tried once, but somehow when i got a log in error, the whole ui changed to what looks like old ui or something.

![2017-11-16_02h29_40](https://user-images.githubusercontent.com/265831/32928039-54d188a6-cb50-11e7-9e75-3b8227b29b5b.png)

**Comment by bdon** [comment]
@bgirardot are you able to log in now successfully? were you logging in via an OSM account you used previously with the export tool, or a new OSM account?

**Comment by fcujorick** [comment]
I have the same problem, I always was logged in, but just logged out and now I see this error. Just a normal OSM account
