### ISSUE TITLE
Adding link to End of the Year campaign

### ISSUE THREAD

**Issue by smit1678** [hotosm/osm-export-tool#280]
@mataharimhairi One request from Fundraising is to add some links to the end of the year campaign. Ideas for how we could add this - maybe a temporary banner?

**Comment by mataharimhairi** [comment]
@smit1678  Sorry, I totally missed this issue! Yes that would have been fine to add a banner, similar to the one that Tasking Manager had. I'm guessing its a little too late now

**Comment by smit1678** [comment]
@mataharimhairi No worries, we can revisit this next year and discuss how to best do this.
