### ISSUE TITLE
Export .obf not working

### ISSUE THREAD

**Issue by ViolaineDo** [hotosm/osm-export-tool#282]
As in the title, I tried to use the export tool for integration in OSMAnd (.obf) but this didn't work : for my export I only got buildings extracted AND only the ones from a long time ago. No roads or POI included.
How can we move forward? If anyone is interested in the development, I / CartONG could help on the process as we set up it for a specific project. 
Thks

**Comment by bdon** [comment]
The export you created "test betou" only includes buildings. When creating an export you can include more features via the tab #3 "Data".

**Comment by ViolaineCartONG** [comment]
Which leads us to the issue : when selecting obf export only, tab "data" disappears

**Comment by bdon** [comment]
May be the same issue as #278 , will investigate

**Comment by ViolaineCartONG** [comment]
thks!

**Comment by bdon** [comment]
@ViolaineCartONG a temporary workaround should be to create both a Shapefile and an OBF, that way the "data" tab will not disappear.

**Comment by ViolaineCartONG** [comment]
@bdon great! :) it's fine for me, thanks !!

**Comment by bdon** [comment]
Changed it to always show Data tab, even if only .obf is selected
