### ISSUE TITLE
Increase MBtiles Export to Level 20

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#283]
The Export Tool only creates MBTiles to level 18, which doesn’t provide enough detail for identifying dense city areas. 

The POSM Export Tool used to created MBTiles to level 20, but this is no longer maintained. Would it be possible to increase the level?

**Comment by bdon** [comment]
I do not think this is feasible. the system already struggles to download a full tileset at maxzoom=18, and increasing it to 20 will increase the # of tiles needed by a factor of 16.

**Comment by mataharimhairi** [comment]
Is there a way to allowed level 20, but greatly reduce the area extent?

**Comment by bdon** [comment]
That would involve a lot of changes to the UI - users would have to specify zoom 20 and then the UI needs to re-validate the selected extent, showing an appropriate validation message.

Is this for a targeted use case that can be implemented in a way independent of the Export Tool?

**Comment by mataharimhairi** [comment]
Its for use in the OpenMapKit android application, so users can access the satellite imagery in the field while collecting detailed attribute information for features on the ground. 

Some areas of the city are very dense, making the visibility of features insufficient at level 18. We also discussed the possibility of adding another satellite imagery provider layer to the app, but thought that would be more involved than modifying the Export Tool.

Based on your feedback, sounds like changes to the Export Tool are also rather involved.

**Comment by bdon** [comment]
This seems like it would make the most sense as part of the OpenMapKit tooling - creating a MBTiles archive out of a set area of satellite imagery

**Comment by mataharimhairi** [comment]
#279

**Comment by bdon** [comment]
@mataharimhairi this has been changed on staging. However the frontend will impose a limit of 5000 tiles, which only works for small areas if zoom=20 is specified. Also, the default OSM.org tiel source only renders raster tiles to zoom level 19.

**Comment by mataharimhairi** [comment]
@bdon great that MBTiles can be created to zoom 20. generally when MBTiles are created for use with OMK, the area is not that large, so setting a limit for this level makes sense. this way the tool won't han on processing these files. as for the default tile source, we'll have to look at alternatives to support level 20
