### ISSUE TITLE
Create stored config doesn't show YAML validation errors

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#284]
Is there a limit to how many configurations a user can have stored? I currently have 5 and can't add any new ones.

**Comment by bdon** [comment]
I was just able to create one. Is it possible there is an error in your YAML? can you paste it here?

**Comment by mataharimhairi** [comment]
You were right @bdon! There was an error with my YAML. Is it possible for a pop-up alert to notify the user of an error in their code, instead of nothing happening?
