### ISSUE TITLE
Can't switch to next stored config page on 03 Data tab

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#285]
Unfortunately I can't switch pages for the stored configurations on the 03 Data tab, by clicking on the page number or '>'. Only way is to type in the config name and search it.

<img width="1276" alt="screen shot 2018-01-23 at 12 45 27" src="https://user-images.githubusercontent.com/8972913/35260522-a6f9457e-003e-11e8-848a-8cfbdc905f44.png">

**Comment by bdon** [comment]
This should be fixed and on staging now.

**Comment by mataharimhairi** [comment]
@bdon i can't test this out on staging, as it won't let me save configs?
