### ISSUE TITLE
Change Export ID to Name

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#286]
Is it possible to change the export ID to the name. The only place the name is present is on the generated file, which can make knowing the correct export a little confusing. 

<img width="1280" alt="screen shot 2018-01-23 at 13 56 08" src="https://user-images.githubusercontent.com/8972913/35265590-1bbc52b6-0053-11e8-9533-5745933156e6.png">

**Comment by bdon** [comment]
The reason the export ID is like that is so it is guaranteed to be unique - it is very likely that two different users create an export called `jakarta` for example
