### ISSUE TITLE
/api/jobs select ALL feature_selection

### ISSUE THREAD

**Issue by danielduhh** [hotosm/osm-export-tool#289]
Is there a way to select ALL OSM features when specifying values for `feature_selection` in the `POST /api/jobs` request ?

If not, I vote adding that feature to the API !

**Comment by mataharimhairi** [comment]
@danielduhh you can select all the OSM features in the area of interest by choosing the PBF file format  on the '2 Formats' tab and Bundle for POSM on the '4 Summary' tab. This will produce a PBF with all the available data!

**Comment by bdon** [comment]
This can be accomplished by specifying a YAML. You can include this in the request if you are using the API. Examples are here: https://github.com/hotosm/osm-export-tool-python/tree/master/osm_export_tool/mappings

You can also copy the result YAML by selecting the checkboxes in the UI.
