### ISSUE TITLE
Authorize access to your account - OpenStreetMap Login Error

### ISSUE THREAD

**Issue by fcujorick** [hotosm/osm-export-tool#293]
Hi, 

Everytime I tried to login on the hotosm.org export page I get:

Authorize access to your account
The application HOT Export Tool is requesting access to your account, *******. Please check whether you would like the application to have the following capabilities. You may choose as many or as few as you like.

Allow the client application to:

- read your user preferences.

When i click on Grant Access, this shows up:

OpenStreetMap Login Error
There was a problem logging you in to OpenStreetMap

Anyone has a solution? it's a bit urgent!

**Comment by mojodna** [comment]
There's a corresponding error on Sentry: https://sentry.io/humanitarian-openstreetmap-tea/export-tool-2-prod-l0/issues/432434736/ (this is for tracking purposes, you won't be able to see it).

The OSM API returned a 500 error when you attempted to log in. It's possibly / likely that that's an intermittent problem on their end, so I'd give it another shot.

**Comment by fcujorick** [comment]
So it's a OSM issue and not Hotexport?
Can't open your link

**Comment by mojodna** [comment]
Pretty sure, yeah. The error message (buried deep in Sentry; don't worry about accessing it) is:

```
503 Server Error: Service Unavailable for url: https://www.openstreetmap.org/oauth/request_token
```

The 503 suggests that it's intermittent on their end / subsequently fixed.

**Comment by mojodna** [comment]
https://github.com/python-social-auth/social-core/commit/6d91240f3416e85bf525e72c0151964206912b57 changes the protocol used to access OSM (which appears to be enforced on the OSM end now).

I'm upgrading `social-app-django` to pick up `social-app-core@1.7.0`.

**Comment by mojodna** [comment]
This should be fixed now.

**Comment by fcujorick** [comment]
Thanks, works :)
