### ISSUE TITLE
Geopackage exports are not clean

### ISSUE THREAD

**Issue by olivierdalang** [hotosm/osm-export-tool#294]
Hi !

Just compared shapefiles and geopackage exports during [my last export](https://export.hotosm.org/en/v3/exports/c4dade8c-e6fd-4d70-a816-90d653d0bb6e/).

The shp export is quite neat, as there are just 3 files/layers : `lines`, `points` and `polygons` (plus the `clipping_boundary.geojson` file)

The geopackage, on the other side, contains 6 layers : `lines`, `multipolygons`, `planet_osm_line_lines`, `planet_osm_point_points`, `planet_osm_polygon_polygons`, `points` (plus `boundary` and a separate `clipping_boundary.geojson` file).
They don't seem to be exactly the same, as they contain similar but different number of features (eg. 5338 for `lines` vs 5304 for `planet_osm_line_lines`).

This makes it difficult to know which ones one is supposed to load. After comparing to the shapefile, it seems the `planet_osm_*` layers are the one that correspond to the shapefile export.

Isn't it be possible to completely remove the other ones from the export ?

Also (but this may not be the export-tool's fault), the `lines`, `points` or `polygons` layers are buggy in QGIS, they appear only a some particular zoom levels (looks like there's a corrupted bounding box or spatial index). The other one work well.

Thanks !

This is how the .gpkg opens in QGIS 3.3 :
![capture](https://user-images.githubusercontent.com/1894106/43621166-1d98d884-972a-11e8-9bb4-069aa604ad7a.PNG)

**Comment by bdon** [comment]
@olivierdalang there is a new standalone library at https://github.com/hotosm/osm-export-tool-python which exports geopackages cleanly. this is running now on http://export-staging.hotosm.org . Can you try it there if possible and let me know if the new file output makes sense to you?
