### ISSUE TITLE
Error in ./app/index.js

### ISSUE THREAD

**Issue by Fabio-Pires** [hotosm/osm-export-tool#298]
After command yarn start at ui/ directory I got the follow error:
------------------------------------ begin
(venv) C:\Users\nt0a\Documents\NetBeansProjects\osm-export-tool-master\ui>yarn start
yarn run v1.9.4
$ ./node_modules/.bin/webpack-dev-server --hot --history-api-fallback --content-base public/
Project is running at http://localhost:8080/
webpack output is served from /static/ui/js/
Content not from webpack is served from C:\Users\nt0a\Documents\NetBeansProjects\osm-export-tool-master\ui\public
404s will fallback to /index.html
Hash: 3dcb623ed83bde1d4933
Version: webpack 3.6.0
Time: 1285ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  901 kB       0  [emitted]  [big]  main
[./app/index.js] ./app/index.js 366 bytes {0} [built] [failed] [1 error]
[./node_modules/babel-polyfill/lib/index.js] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 6.74 kB {0} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {0} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.23 kB {0} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.04 kB {0} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
   [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?
http://localhost:8080 ./app/index.js 88 bytes {0} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.04 kB {0} [built]
    + 400 hidden modules

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/clien
t?http://localhost:8080 ./app/index.js
Module not found: Error: Can't resolve 'react-hot-loader/patch' in 'C:\Users\nt0a\Documents\NetBeansProjects\osm-export-tool-master\ui'
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?http
://localhost:8080 ./app/index.js

ERROR in ./app/index.js
Module parse failed: C:\Users\nt0a\Documents\NetBeansProjects\osm-export-tool-master\ui\app\index.js Unexpected token (11:4)
You may need an appropriate loader to handle this file type.
| const render = Component =>
|   ReactDOM.render(
|     <AppContainer>
|       <Provider store={store}>
|         <Component history={history} />
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill react-hot-loader/patch webpack-dev-server/client?http
://localhost:8080 ./app/index.js
webpack: Failed to compile.
-------------------------------------------------- end
I tried everything: upgrade yarn, upgrade webpack, tried out of venv enviroment and nothing.
I think that a problem about versions of packages (oldest) but I'm not sure.
Does anybody can help?
Thanks in advanced.
Fabio Pires.

**Comment by bdon** [comment]
This should be fixed now - the issue was forward vs backward flashes in the webpack config for Windows.
