### ISSUE TITLE
Permalink for latest export

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-export-tool#304]
Would be really useful to have a permalink to the latest download for each export. This would allow linking downloads from an external website, and run manual updates without having to change the link each time.

**Comment by bdon** [comment]
As-is, generated exports will be deleted after 90 days. If we allow an option for permalinks, it would require never expiring exports that choose that option. I suspect many users who create exports will choose the permalink option, potentially resulting in an infinitely growing storage requirement for the application. @cgiovando @mataharimhairi do you think it would be reasonable to limit permalinks to only pre-approved users, such as for HOT projects or partners?

**Comment by mataharimhairi** [comment]
@bdon I think the ability to create permalinks for exports should only be available to pre-approved users. This functionality will generally be used when creating exports for partners on projects who want to access certain OSM data easily through pre-set jobs linked in reports, presentations, etc. Having the ability to provide partners the ability to setup their own jobs with permalinks would also be very useful, in which case we would pre-approve them.

**Comment by mataharimhairi** [comment]
@bdon just adding the update from our conversation here. the same 'Admin' access would allow users to run as many jobs as they like, in addition to creating permalinks.

**Comment by bdon** [comment]
@mataharimhairi the "partners" feature is now live in production and can be used the same way as for PDC.
