### ISSUE TITLE
Some relations are not exported

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool#306]
Eg this natural=wetland relation [https://www.openstreetmap.org/relation/3827805#map=12](https://www.openstreetmap.org/relation/3827805#map=12/9.2523/-13.2606) that is correctly mapped is not exported in the polygon shapefile from [https://export.hotosm.org/fr/v3/exports/53f389d2-0357-4331-8e40-85474071dbdc/](https://export.hotosm.org/fr/v3/exports/53f389d2-0357-4331-8e40-85474071dbdc/)

**Comment by bdon** [comment]
I think this is working now:

https://export.hotosm.org/en/v3/exports/d380e1ba-fcb9-4a21-a672-53b89e7c18f0


![Screen Shot 2019-07-30 at 9 14 38 PM](https://user-images.githubusercontent.com/77501/62183453-1a61a900-b30f-11e9-9b10-58af6b3455ad.png)

Can you confirm?

**Comment by mataharimhairi** [comment]
@bdon Just did a quick export test (https://export-staging.hotosm.org/en/v3/exports/3b1206e0-5ef0-4fd3-93a5-97c4cccc4b74), and need to look into it further. It looks like the relations are now being exported through staging, and is showing up as expected in JOSM:

<img width="1348" alt="Screen Shot 2019-08-01 at 16 51 13" src="https://user-images.githubusercontent.com/8972913/62334500-c4ab0f00-b47c-11e9-8f8a-bfd6af5ada8c.png">

However it looks like some of the relation polygons are missing when the same shapefile is opened up in QGIS. Another side note is regarding the shape and geopackage file format, which still contains unnecessary layers (i.e. point layer when there is no point data requested or present):

<img width="1392" alt="Screen Shot 2019-08-01 at 16 51 04" src="https://user-images.githubusercontent.com/8972913/62334561-0045d900-b47d-11e9-8d34-68fb22f5633d.png">

**Comment by bdon** [comment]
For the first issue (missing relations), can you try it on the live site export.hotosm.org and see if it is missing the same relations?

For the extra layers, #294 should address this

**Comment by mataharimhairi** [comment]
Looks like staging and live have the same number of relations in the attribute table, but the polygons being displayed are different in QGIS. Both the SHP and GPKG files seem to have the same number of attributes when opened in QGIS and JOSM, but only all of the polygons are being displayed as expected in JOSM. 

Staging
https://export-staging.hotosm.org/en/v3/exports/f80a92f3-383e-44b5-a003-f009ed37a314

Live
https://export.hotosm.org/en/v3/exports/17874d94-1ad9-4956-9065-b898ad9b47c1

**Comment by bdon** [comment]
@mataharimhairi how are you loading the information into JOSM, can you include a screenshot of the exact difference you are seeing?

**Comment by mataharimhairi** [comment]
@bdon please see the screenshots above. that is the difference i am getting between opening up the same data in JOSM and QGIS. all the data is present in both platforms, but they are only fully rendering in JOSM. you can try it with the extract datasets in the above export tool link.

**Comment by bdon** [comment]
@mataharimhairi yes, I understand the screenshots. Via which steps are you loading the SHP or GPKG into JOSM though, or are you loading the PBF? If you are loading the GPKG in JOSM, is it through a plugin? If you are loading the PBF in JOSM, it makes sense that it has more information than the GPKG, because the GPKG only has the features which are specified by the YAML, while the PBF is unfiltered.

**Comment by mataharimhairi** [comment]
@bdon I am loading both the GPKG and SHP files into QGIS through 'Add Vector' function which both have 895 attributes in the polygon file. The GPKG renders more of the features than SHP but is still not complete:

<img width="1392" alt="Screen Shot 2019-08-16 at 10 40 25" src="https://user-images.githubusercontent.com/8972913/63187357-86ccef80-c013-11e9-9316-9d86c59d5f87.png">
GPKG

<img width="1392" alt="Screen Shot 2019-08-16 at 10 42 00" src="https://user-images.githubusercontent.com/8972913/63187373-92201b00-c013-11e9-9356-3979296c0270.png">
SHP

Then I am loading the SHP file into JOSM with the Open Data plugin, which appears to be rendering as expected:  

<img width="1351" alt="Screen Shot 2019-08-16 at 10 46 33" src="https://user-images.githubusercontent.com/8972913/63187390-9cdab000-c013-11e9-9538-5f0d8176819d.png">
SHP

Hope this helps to clarify the situation. Both GPKG and SHP files were re-run from the following job https://export-staging.hotosm.org/en/v3/exports/f80a92f3-383e-44b5-a003-f009ed37a314

**Comment by bdon** [comment]
@mataharimhairi the GPKG and SHP load the same data for me in QGIS (which also matches JOSM). I think what is happening is the order you are loading the GPKG puts the polygons layer above the lines layer, so if you switch those it should be correct.

**Comment by mataharimhairi** [comment]
@bdon I'm not loading the line files for the GPKG and SHP, only the polygon files as the data should only be exporting polygons for relations.

**Comment by bdon** [comment]
@mataharimhairi can you check again with the new code? https://export-staging.hotosm.org/en/v3/exports/f80a92f3-383e-44b5-a003-f009ed37a314

**Comment by mataharimhairi** [comment]
@bdon i just checked the datasets extracted with the new code and tested the SHP files both in JOSM and QGIS. it appears to be rendering correctly in JOSM but not in QGIS (there is only an outline of the bounding box but all relations are present in the attribute table):

<img width="1348" alt="Screen Shot 2019-11-12 at 16 20 10" src="https://user-images.githubusercontent.com/8972913/68664633-c0f15300-0568-11ea-96de-e17a348c0d08.png">

<img width="1392" alt="Screen Shot 2019-11-12 at 16 21 00" src="https://user-images.githubusercontent.com/8972913/68664669-ca7abb00-0568-11ea-9234-41337e415625.png">

**Comment by bdon** [comment]
@mataharimhairi can you try changing the rendering mode in QGIS? You need to change the opacity to lower and choose a fill style with borders. The issue may be that there is one huge boundary relation that is clipped to the box, and covering the other ones. see my screenshot 

<img width="840" alt="Screen Shot 2019-11-12 at 5 34 20 PM" src="https://user-images.githubusercontent.com/77501/68716692-ce133f80-0572-11ea-94a1-0ec8f30e1647.png">

**Comment by mataharimhairi** [comment]
@bdon it worked! the relations are visible now once changing the opacity or selecting a fill style. is there a way to help automatically display this though? worried that end users will also think there is something wrong with the file when they open it in QGIS. although they could be a little more investigative than I was ...

**Comment by bdon** [comment]
There isn't really a way to automatically display this without outputting QGIS project files to specify a rendering style. This issue really only affects features types where there are likely to be large parent polygons with many levels of child polygons, such as admin boundaries.
