### ISSUE TITLE
Spilt HDX POIs into Baseline Preparedness Categories (GRID)

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#309]
HDX have set up 'Data Grids' to assist users find the right and relevant data. These grids place the most important crisis data into six groups: affected people; coordination and context; food security and nutrition; geography and infrastructure; health and education; and population and socio-economic indicators:

https://centre.humdata.org/introducing-the-hdx-data-grid-a-way-to-find-and-fill-data-gaps/

Currently the OSM data exported through the Export Tool for airports, health facilities and education facilities are lumped into one datasets - POIs, which makes it difficult for HDX to include in the Data Grid and for users to apply. Perhaps these should be exported and hosted on HDX as individual files?

Another dataset for inclusion would be populated places, which could be extracted from OSM as the boundaries of cities, towns, etc @PaulUithol

**Comment by jessbeutler** [comment]
Discussed HDX exports with the regional OCHA Latin America and Caribbean team, as they are in need of school OSM exports for the development of a regional COD for disaster response. At the moment, this data is available through POI exports, but can be time consuming and not ideal to manually separate in an emergency scenario.

**Comment by mataharimhairi** [comment]
Chatted with @cjhendrix from HDX this morning to discuss break out datasets from the current POI's, which will include airports, health facilities and education facilities. These will be removed from the POI dataset and become standalone files. Other datasets to be created include populated places. 

Administrative boundaries were also discussed, but determined that these should be left out again due to their sensitive nature. Informal settlements (IDP and refugee camps) were also discussed and will be investigated for potential inclusion in the future @TylerRadford @PaulUithol

**Comment by TylerRadford** [comment]
Hi this sounds great @mataharimhairi and thanks for the update. Glad we are moving on this so quickly! Is this already covered in the current development round / what is the LOE for us and for HDX side? Release date?

**Comment by mataharimhairi** [comment]
Hey! Yes this is covered in the current development and shouldn't take that much work, mainly re-evaluating the data model and then pushing the changes to the YAML syntax on the Export Tool. We may have to manually make the changes to the older datasets so they pick up it up but we'll know for sure in a couple weeks. Should be done by end of August @TylerRadford

**Comment by mataharimhairi** [comment]
Started with the Health Facilities dataset since I've been working on the data model for the https://wiki.openstreetmap.org/wiki/Global_Healthsites_Mapping_Project initiative. Please check it out and provide comments directly on the document(s) @TylerRadford @PaulUithol @cjhendrix. There are two versions of the health facilities data model, a simplified and a complete version:

https://drive.google.com/drive/u/0/folders/124a-vbpAn2Sq6XxhkNh1THnRN11w5SAl

Not quite sure which would be more appropriate for HDX and would be good to discuss. My initial thoughts would be to go with the simplified, as the complete version might have an overwhelming amount of information (when not empty). And users can opt to obtain the complete version from https://data.humdata.org/organization/healthsites once the datasets are populated.

**Comment by cjhendrix** [comment]
Could we talk through the implications with the healthsites data?  I think it may be confusing for users to have two different, largely overlapping versions of the health fac data.  Although maybe having "full" and "simplified" versions makes sense if they reference each other in the descriptions.

**Comment by mataharimhairi** [comment]
The new OSM datasets (airports and helipads, education facilities, health facilities, populated places, railways and ferry terminals) that are being added to HDX can be found in the following folder, which already have the correct HDX tags in the YAML code:

https://drive.google.com/drive/u/0/folders/124a-vbpAn2Sq6XxhkNh1THnRN11w5SAl

**Comment by mataharimhairi** [comment]
The updated YAML txt including the financial services, and the seaport dataset which is now combined with the airport dataset can be found in the Google Docs folder above @bdon

**Comment by mataharimhairi** [comment]
Created 3 test countries (Costa Rica, Greece and French Guiana) with the new datasets supporting the ‘Grid’ feature. they are currently available as ‘private’ datasets on HDX:

**Costa Rica**
https://export.hotosm.org/en/v3/hdx/edit/308
https://data.humdata.org/organization/hot?q=Costa%20Rica&ext_page_size=25 

**Greece**
https://export.hotosm.org/en/v3/hdx/edit/310
https://data.humdata.org/organization/hot?q=Greece&ext_page_size=25&sort=score%20desc%2C%20max(last_modified%2Creview_date)%20desc

**French Guiana**
https://export.hotosm.org/en/v3/hdx/edit/311
https://data.humdata.org/organization/hot?q=french%20guiana&ext_page_size=25&sort=score%20desc%2C%20max(last_modified%2Creview_date)%20desc

**Comment by bdon** [comment]
@mataharimhairi I have scripted the update for the new YAML on export-staging.hotosm.org, so all HDX regions should have it now. Please test to confirm on staging before I move to prod.
