### ISSUE TITLE
Add Data Models as Core YAML Configurations

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#310]
It would be good to add some of the data models that HOT has been working on over the last couple of years to the tool, as options to apply to exports in YAML syntax. Ideally these would be featured/highlighted on the landing page, as well as appear in everyones 'Stored Configurations'.

Some of the data models include:

* Global Exposure Database for All
* Sustainable Development Goals
* Humanitarian Data Exchange
* Healthsites.io

**Comment by mataharimhairi** [comment]
@bdon how easy is it for us to implement this? i have the data models ready to go and would really like the ones listed above to be available to all users as default config options in their YAML configuration library for easy access!

**Comment by bdon** [comment]
This can be done by adding to the "Configurations" section and then setting the Pinned checkbox.

**Comment by mataharimhairi** [comment]
@bdon have pinned the YAML configurations for the Global Exposure Database for All,Humanitarian Data Exchange and Healthsites.io data models.

**Comment by bdon** [comment]
on export-staging.hotosm.org
