### ISSUE TITLE
Review Bundle Export Functionality

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#311]
Provide a clearer option for users to select all tags available in an AOI for the PBF file format during the export set up process. At the moment this is available through selecting the POSM Bundle on the Summary tab.

![Screen Shot 2019-06-03 at 11 33 06](https://user-images.githubusercontent.com/8972913/58825586-a303e780-85f3-11e9-9d27-fa2889cbe67a.png)

**Comment by mataharimhairi** [comment]
@bdon we need to change the wording for 'Bundle for POSM' as previously discussed. Many of our users do no know what POSM is and are missing the opportunity to use its functionality to export all available data within their AOI in the OSM .pbf file format. This should perhaps be re-worded to 'Export all OSM data - this will be provided for the AOI as a .pbf'

**Comment by bdon** [comment]
@mataharimhairi "Bundle for POSM" previously created "unfiltered" PBF exports but with the new code all PBFs are unfiltered. So this may not be necessary at all.

**Comment by bdon** [comment]
The "Bundle for POSM" and "Unfiltered" are now two separate checkboxes. 

<img width="319" alt="Screen Shot 2019-11-20 at 11 00 05 AM" src="https://user-images.githubusercontent.com/77501/69254908-edb6f300-0b84-11ea-91e6-0940ba9391ba.png">

**Comment by mataharimhairi** [comment]
@bdon can we change the text to 'Unfiltered files - all OSM data for PBF, MWM, OBF and IMG formats'
