### ISSUE TITLE
Milestone 1. Setup staging instance on Azure

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#314]

**Comment by bdon** [comment]
- [ ] We should get a floating IP and a DNS entry for export-staging.hotosm.org to point to it. This will let us re-create the staging instance without having to reassign the name each time.

**Comment by bdon** [comment]
@mojodna what is the Callback URL for the OSM OAuth application? you can see this on osm.org > my settings -> oauth -> my client applications -> edit details

**Comment by bdon** [comment]
@mojodna nevermind, determined it is https://export.hotosm.org/authorized (the issue was that the OAuth library requires the redirect to be SSL, it will fail with an unrelated error if the redirect is plain HTTP)

**Comment by mojodna** [comment]
Awesome, sorry for not pitching in sooner; just wrapped up a move (in-town) over the weekend.

**Comment by bdon** [comment]
Instead of using the new Maps.ME generator, I copied over the binary from the existing working version. So maps.me works now on staging, using the same version as before.
