### ISSUE TITLE
building:part not considered a polygon

### ISSUE THREAD

**Issue by dforsi** [hotosm/osm-export-tool#319]
`building:part` is documented in the [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:building:part) as "may be used on areas", and only on areas, so I think you could add this tag in this line of your `utils/geopackage.py`
> closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,harbour,historic,landuse,leisure,man_made,military,natural,office,place,power,shop,sport,tourism,water,waterway,wetland

thank you

**Comment by bdon** [comment]
Thanks for reporting this - I'll make this change in the new version of the Export Tool that will be coming later this summer.

**Comment by bdon** [comment]
Has been updated on staging which is running the old conversion code - issue for the new code also tracked here: https://github.com/hotosm/osm-export-tool-python/issues/5
