### ISSUE TITLE
Milestone 3. Secondary Pipeline

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#322]
@bdon notes : 

> Began osm-export-tool-python repo: https://github.com/hotosm/osm-export-tool for new more efficient export pipeline - can now be installed via `pip install osm-export-tool` Benchmarked this against Indonesia .PBF, which can complete in about 1.5 hours for unfiltered OSM features with < 1GB of RAM.

**Comment by bdon** [comment]
Notes: On azure disk ("premium SSD"), a day of diffs takes 2 hours to apply

```
(venv) exports@ExportToolStaging:/mnt/data/planet$ time osmium apply-changes planet-latest.osm.pbf 512.osc.gz -o planet-new.osm.pbf

real    127m7.334s
user    173m42.825s
sys     9m32.823s
```

**Comment by bdon** [comment]
This is now on production; hotosm_tza (Tanzania) can now run without having to split into parts: the "planet file" checkbox needs to be checked, which will use the non-Overpass source data.

**Comment by bdon** [comment]
Issue #300 addresses merging all the sectioned country datasets.
