### ISSUE TITLE
PBF file is not zipped anymore

### ISSUE THREAD

**Issue by hedderich** [hotosm/osm-export-tool#340]
This is more a question than an issue, but I noticed that pbf files never seem to be exported as zip archives anymore, is that intended? Old exports still have the link to a zip archive while new ones link directly to the pbf and I couldn't find this change documented anywhere.

**Comment by bdon** [comment]
@hedderich this is correct and intended, because OSM PBFs are already compressed internally, so zipping the file isn't very useful. Can you direct me to the old export you're using that has the broken link?

**Comment by hedderich** [comment]
The link was never broken, it links correctly to the old zip file 🙂
I was just curious if the change was intended or not and yeah it makes sense to not compress the PBF again 👍
