### ISSUE TITLE
POSM Bundles empty

### ISSUE THREAD

**Issue by jonnyhuck** [hotosm/osm-export-tool#343]
In exports such as these:
[https://export.hotosm.org/en/v3/exports/d8c87f3a-e708-4c39-ab7f-9394223be164](https://export.hotosm.org/en/v3/exports/d8c87f3a-e708-4c39-ab7f-9394223be164)
[https://export.hotosm.org/en/v3/exports/9b402144-018f-4e81-b589-cc35e7c3606f](https://export.hotosm.org/en/v3/exports/9b402144-018f-4e81-b589-cc35e7c3606f)

The .pbf dataset is not located inside the bundle, it contains only `manifest.json` (nothing else, no directories or anything), which reflects the fact that it is empty in its `contents` property:
```
{
  "title": "Gulu",
  "name": "Gulu",
  "description": "For Gulu Huckathon Jan 2020",
  "bbox": [
    32.19411779564929,
    2.695741818683331,
    32.393754356083,
    2.8752023643171754
  ],
  "contents": {}
}
```
Does anyone know why this might be? 

I have attemted to replicate the structure of the bundle, but so far I have not been able to get it to work in POSM (which I realise isn't an issue for here).

**Comment by bdon** [comment]
Thanks for reporting this, it should be fixed now: https://export.hotosm.org/en/v3/exports/9b402144-018f-4e81-b589-cc35e7c3606f
