### ISSUE TITLE
arabic lang

### ISSUE THREAD

**Issue by aat765** [hotosm/osm-export-tool#344]
i have problem that when i export to garman .img not show arabic lang of objects and ways

**Comment by bdon** [comment]
@aat765 can you confirm that the OSM elements you are interested in have Arabic-language `name` or `name:*` tags?

**Comment by aat765** [comment]
yes pls

**Comment by bdon** [comment]
@aat765 sorry, I meant can you provide a link to OSM to demonstrate an example of arabic-language tags that do not appear in the export.

**Comment by aat765** [comment]
https://export.hotosm.org/en/v3/exports/d8f6ebb5-f423-44db-9a60-2933a3608a78

**Comment by bdon** [comment]
Hi,

There is only very limited name information in OSM for that area, but it is in Arabic: https://www.openstreetmap.org/node/1236399743#map=15/25.6755/45.4558 It's mostly for place nodes such as village. Is this different from the result you were expecting in the Garmin .IMG format?

**Comment by aat765** [comment]
i want to use it on other area that have a lot of arabic name's, and yes that's different from the result i expecting in Garmin .IMG format, it support arabic lang and i think maybe the problem in encoding most be support UTF-8 (8-bit Unicode Transformation Format).

thank you

**Comment by bdon** [comment]
Can you confirm that other IMG files from other sites can display Arabic text correctly on your device?

This is how our .IMG is generated: https://github.com/hotosm/osm-export-tool-python/blob/master/osm_export_tool/nontabular.py#L71 I don't see anything specific to Unicode here.

**Comment by aat765** [comment]
trey this map it is in arabic and img and working with garmin:
https://www.mediafire.com/file/ij1xf1t9rmfpx13/Hail.img/file

maybe the problem in mkgmap_jar not support arabic.

**Comment by bdon** [comment]
@aat765 I have patched the server temporarily to generate Garmin IMG files with the `--unicode` option. I ran your previous export job again: https://export.hotosm.org/en/v3/exports/d8f6ebb5-f423-44db-9a60-2933a3608a78 

Can you tell me if this fixes the Arabic label display issue?

Even if so, this change increase the size of the IMG files by a lot, so I am not confident we can make this change for all files. Will need to observe for a while.

**Comment by aat765** [comment]
yes it's fixed now thank you so much for your time and efforts

**Comment by bdon** [comment]
Resolved by eb4231b14926f92231bcfcb7d45fcb7cc8408b9a
