### ISSUE TITLE
missing towns and villages from place exports

### ISSUE THREAD

**Issue by lukaszkruk** [hotosm/osm-export-tool#346]
When creating a new export task on https://export.hotosm.org/en/v3/, I proceed to step 3 and in the Tag Tree select 'localities' > 'places'. The query reads 

`Where: place IN ('country','state','region','province','district','county','municipality','city','borough','suburb','neighbourhood')`

'town' and 'village' seem to be obvious omissions from this list.

Including a screenshot (which is maybe not very helpful as the query is truncated):

![image](https://user-images.githubusercontent.com/2972523/83871136-cd6d1100-a72f-11ea-9206-87218789b614.png)

**Comment by lukaszkruk** [comment]
@bopercival-hot is this something you could help with?

**Comment by dakotabenjamin** [comment]
I'm not too familiar with the code for this tool but I think changes need to be made in two places: 
https://github.com/hotosm/osm-export-tool/blob/bae18debbd0db81f0ec5a0b235a0ec2998bcae91/ui/app/utils/TreeTagSettings.js#L817
https://github.com/hotosm/osm-export-tool/blob/bae18debbd0db81f0ec5a0b235a0ec2998bcae91/ui/app/utils/tagtree.csv#L52

@bdon am I missing something?

**Comment by lukaszkruk** [comment]
Hello @dakotabenjamin, do you think there's a chance this issue will be fixed?

**Comment by dakotabenjamin** [comment]
@lukaszkruk yes I would like to have this fixed as well. We are working on prioritizing it, but are also happy to receive pull requests in the meantime.

**Comment by lukaszkruk** [comment]
Alright, I will try to do a PR. Based on https://github.com/hotosm/osm-export-tool/commit/749193da315d06c8057ea29a88b67097142f2236 it looks like the two places you mentioned above are the only ones to change.

**Comment by bdon** [comment]
@lukaszkruk can you verify that this works as expected on export.hotosm.org ?

**Comment by lukaszkruk** [comment]
Indeed it does, thanks for the merge.

**Comment by bdon** [comment]
Great! Thanks for your contribution.
