### ISSUE TITLE
Increase disk space for Postgresql data

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/osm-export-tool#378]
Per discussion w/ @eternaltyro - export tool was down today due to DB crash issues. On further investigation, we found the disk partition had 100% of the space utilised. As an immediate solution cleared up some cache and got the service back. However as an extended solution we should make more storage space available for Postgres data.

cc @dakotabenjamin @JorgeMartinezG @robsavoye

**Comment by eternaltyro** [comment]
Added an extra 32GB disk, copied PostgreSQL data to it, and mounted it on to `/var/lib/postgresql`.
