### ISSUE TITLE
Import a new copy of the planet for the new production deployment

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/osm-export-tool#401]
Now that we have the staging up at https://export-staging.hotosm.org/ - we will leave it for testing till end of June. After mid-July we will go with the production deployment with the new data source. For this we will need the entire OSM bootstrapped from planet source and then we can have the script running to update the data continuously.

@itskshitiz321 will lead the efforts for data loading.

cc @eternaltyro @dakotabenjamin

**Comment by ramyaragupathy** [comment]
Related to https://github.com/hotosm/osm-export-tool/issues/402

**Comment by kshitijrajsharma** [comment]
Deployed in Aug1 and tested !
