### ISSUE TITLE
Production deployment with Galaxy API data source

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/osm-export-tool#402]
@dakotabenjamin @eternaltyro @itskshitiz321 - let's use this ticket to track tasks on production deployment.

**Comment by itskshitiz321** [comment]
Plan is to Use following Specs : 
**For the Planet loading :**
We will have one ec2 with ( 4 VCPU / 32 GB of RAM and 500 GB of Storage with high I/O) , R6g.XLarge
** RDS :** 
R6g.XLarge : 4/32 with 2 TB of Space - Auto scaling up to threshold max 5 TB

**Comment by kshitijrajsharma** [comment]
Export tool deployed to same machine , and Planet has been loaded and captured in another ticket
