### ISSUE TITLE
Unwanted Buffers created on the output data and boundary 

### ISSUE THREAD

**Issue by ghimiresushma99** [hotosm/osm-export-tool#406]
I was trying to export data using a geojson file of Itahari Sub-Metro, Nepal as follows:

![Screenshot (4)](https://user-images.githubusercontent.com/80664831/176091929-e772a553-3d1f-419e-bad8-c5862a252f3a.png)

But after the processing is complete, you can see the boundary file has changed in the following screenshot. 

![Screenshot (5)](https://user-images.githubusercontent.com/80664831/176092196-ec405df7-1c67-4af0-b641-243b444610da.png)

The buffer has been created although I didn't select the activate buffer option.

I visualised the data in GIS and noticed the data outside of my original AOI has also been downloaded. The extent of AOI has been revised and it's the updated-buffer-boundary now (labelled as clipping boundary in the screenshot).

![Capture](https://user-images.githubusercontent.com/80664831/176092430-b5df7fd7-1e46-452c-a28c-238cd0ca2530.PNG)

**Comment by kshitijrajsharma** [comment]
Hi @ghimiresushma99 , thank you for providing so much details in the issue, this will surely help developer to look in to it.
Meanwhile, Currently we are testing geojson and shapefile option on our staging [server](https://export-staging.hotosm.org/ ) , If possible can you try same export on staging server and visualize the clipping boundary ? To see either it also has the same error or not !

**Comment by kshitijrajsharma** [comment]
I can verify that this bug is due to the feature that export tool simplifies the geometry if geometry contains too many points to make query faster ! Using galaxy this can be enhanced and put in to consideration as galaxy supports complex geometry as well

**Comment by ghimiresushma99** [comment]
![image](https://user-images.githubusercontent.com/80664831/177253940-7039518d-ad49-4ae1-9c25-32c32d7aafff.png)

The issue is similar in the staging server too. 

The geometry is oversimplified which does not meet the objective of specifying AOI by giving a boundary of that region. 

If simplification of the boundary is necessary to ensure the fast operation of the query, this simplification can be reduced such that the out-of-boundary data, which is usually unnecessary to users is not exported as well.

**Comment by kshitijrajsharma** [comment]
This feature is live on our staging [server](https://export-staging.hotosm.org/ ) , You can use Preserve Geometry Option on the Summary @ghimiresushma99
