### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by igorlaltuf** [hotosm/osm-export-tool#417]
I requested the export of data from a municipality in pbf format and after eight hours the file was not generated. 

Is this common or is it a bug?

url: https://export.hotosm.org/en/v3/exports/5faf3f08-901e-446a-aace-6302865cf598

**Comment by kshitijrajsharma** [comment]
Hi ! Thank you for the report , Problem has been acknowledged and developer is working on fix !

**Comment by kshitijrajsharma** [comment]
Fixed with the PR !
