### ISSUE TITLE
Workers are stuck when CPU usage is high 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/osm-export-tool#421]
Usually , When worker on scheduled service is running it end up eating 100 % of CPU and now due to which any exports running on on demand are stuck ! 
cc: @dakotabenjamin @ramyaragupathy 
This is screenshot when there was a  schedule job running 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/36752999/185791299-6129068a-9c23-46b5-82f1-217ad6de7219.png">

**Comment by dakotabenjamin** [comment]
I can upgrade the virtual machine size. Currently 2vCPU and 14GB Memory. Is the memory near or hitting the limit in the past month? We can go to 4vCPU but I want to understand the memory needs as well.

**Comment by dakotabenjamin** [comment]
But also, can we look into how export tool is using the memory? Even if we increase the cpu capacity, we may still hit a limit unless we optimize the program to control its own usage.

**Comment by kshitijrajsharma** [comment]
added cpu usage monitoring and closing this issue as completed for now , since we can further work on it if cpu crosses the limit
