### ISSUE TITLE
Script to restart on demand workers automatically

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/osm-export-tool#423]
On-demand workers get stuck for reasons like,
* Overpass failure
* CPU utilisation or
* some other unknown reasons

@kshitijrajsharma is working on a script to restart the on demand workers whenever a run is stuck for more than 1 hour. This is a temporary fix for the Export Tool to run without any manual intervention. Architectural fixes should fix this long term.

**Comment by kshitijrajsharma** [comment]
Done ! And not needed anymore , since we are not receiving worker stuck problem ! Even if we did , script is inside the prod env !
