### ISSUE TITLE
Move from OAuth 1.0a to OAuth 2.0

### ISSUE THREAD

**Issue by pnorman** [hotosm/osm-export-tool#513]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by danieldegroot2** [comment]
Also, "using OAuth 1" text in [API.js](https://github.com/hotosm/osm-export-tool/blob/503e5424b90d39885d47af866b7126ab62195daf/ui/app/components/help/API.js#L36) and "OAuth" in [setup-development.md](https://github.com/hotosm/osm-export-tool/blob/503e5424b90d39885d47af866b7126ab62195daf/docs/setup-development.md?plain=1#L5) should be replaced with "using OAuth 2".

**Comment by mmd-osm** [comment]
**Important update**: Operations Working Group has published  timelines for sunsetting OAuth 1.0a: https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490

**Comment by kshitijrajsharma** [comment]
Hi ! Thanks for this ! I will work on this as top priority this month !
